### ISSUE TITLE
Turrets Description 

### ISSUE THREAD

**Issue by ZaynoxTv** [l0th3r/TD-Template#12]
Hello Cosmo, 

We would like to have if it was possible to add some text below the name of each turret to describe its different functions ?

Have a nice day ! 

BERTHOLLET Anthony & PASCOLI Théo - 1 Bachelor Game Design - Bellecour Ecole

**Comment by l0th3r** [comment]
Hi,
Yes it is possible, can you please describe what you need to be written ?
