### ISSUE TITLE
Invalid path arrows

### ISSUE THREAD

**Issue by MartinCHTITI** [l0th3r/TD-Template#2]
When setting up a path, the green arrows used to underline it will either not appear or will appear until a certain point then stop.

![Screenshot_GreenArrows](https://user-images.githubusercontent.com/97921598/167179475-77715ece-82c0-400b-9952-3e5b73f35528.png)

**Comment by l0th3r** [comment]
Hello, is it happening every time ? Did you try changing the rest of the path to another platform and then re-switch them to path platforms ? If not maybe you can try that. Sorry for the inconvenience.

**Comment by MartinCHTITI** [comment]
Apologies for the late answer.

After further experimentations, changing the path does not fix the issue. The arrows stop in most cases at the second path platform. It is entirely possible we're missing something during the setup, however, particularly regarding the setup of the objective.

**Comment by l0th3r** [comment]
Hello, I will investigate the problem on my side. In the mean time, please check that you followed every steps in those tutorials : 
[wiki/TD-WT-v1.1](https://github.com/l0th3r/TD-Template/wiki/TD-WT-v1.1)
[wiki/TD-WT-v1.2](https://github.com/l0th3r/TD-Template/wiki/TD-WT-v1.2)

Please also try to start those steps over so we are sure it is a recurrent issue. Thanks.

**Comment by MartinCHTITI** [comment]
The issue seems to be solved, apparently changing the type of a platform also changed its name, which messed up with the wave manager. Thanks for your concern.
