### ISSUE TITLE
Gameplay addition n°1: Money Producing Turret

### ISSUE THREAD

**Issue by MartinCHTITI** [l0th3r/TD-Template#7]
We would like to add a turret that does not attack ennemies, but instead produce a certain amount of money on a regular basis.

**Comment by l0th3r** [comment]
Yes of course, I would like you to specify the behaviour with a specification of every new mechanics added, like doing a list of every new or modified elements.

**Comment by MartinCHTITI** [comment]
Apologies for late response.

The turret will give the player money on a regular basis (1 gold every 5 seconds). The effect lasts as lond as the turret is alive.

By the way, we must finish our project for around June 5, so we would like to know if you will be able to incude every addition we requested, and if not which can be included.

Thanks for your attention.

**Comment by l0th3r** [comment]
Thank you for your reply.

Does the money generation remplace the weapon ? Or it's another mechanic. If the money generation remplace the weapon, I will just work on a weapon that generate money and make you a turret with it.

In any way, this functionality will be added before June 5.

**Comment by MartinCHTITI** [comment]
Hello.

Since the turret does not attack and only produces money, I guess it replaces the weapon. I'm not sure however what that would change mechanically speaking.

Thanks for your attention.

**Comment by l0th3r** [comment]
Hello,

The tower is added to the new patch. I will release it soon.
For the moment you can set two variables on the new "Miner" weapon.
`(float) Cool Down` which is the time between each money generation in seconds.
`(int) Money Amount` which is the amount of money generated at each generation.

Do you think about something else you want to add to this weapon ?
(It doesnt have a model and no visual effects).
